name: api-websocket-rx
base: core22
version: '1.0.1'
summary: WebSocket API para ctrlX CORE
description: |
  API con WebSocket y FastAPI para conectarse al PLC vía OPC UA.

grade: stable
confinement: strict

architectures:
  - arm64

parts:
  websocket-api:
    plugin: python
    source: .
    python-packages:
      - fastapi
      - uvicorn[standard]
      - websockets
      - opcua
      - python-dateutil
      - pytz
      - lxml
      - colorama
      - six
      - typing_extensions
      - sniffio
      - anyio
      - starlette
      - click
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/websocket-wrapper.sh $SNAPCRAFT_PART_INSTALL/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/websocket-wrapper.sh

apps:
  websocket-api:
    command: bin/websocket-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
