name: api-websocket-rx
base: core22
version: "1.0.0"
summary: WebSocket API para ctrlX CORE
description: |
  API con WebSocket y FastAPI para conectarse al PLC vía OPC UA.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  websocket-api:
    plugin: dump
    source: .

    build-packages:
      - python3.10-venv
      - python3-pip
      - python3.10-dev
      - build-essential

    stage:
      - main.py
      - plc/**
      - ws/**
      - utils/**
      - frontend/**
      - bin/websocket-wrapper.sh
      - requirements.snap.txt

    override-build: |
      craftctl default
      python3 -m venv $CRAFT_PART_INSTALL/venv
      $CRAFT_PART_INSTALL/venv/bin/pip install -U pip setuptools wheel
      $CRAFT_PART_INSTALL/venv/bin/pip install -r requirements.snap.txt
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp bin/websocket-wrapper.sh $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/websocket-wrapper.sh

apps:
  websocket-api:
    command: bin/websocket-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
