name: api-websocket-rx
base: core22
version: "1.0.0"
summary: WebSocket API para ctrlX CORE
description: |
  API con WebSocket y FastAPI para conectarse al PLC vía OPC UA.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  websocket-api:
    plugin: nil
    source: .

    build-packages:
      - python3
      - python3-venv
      - python3-pip
      - python3-dev
      - build-essential
      - rsync

    override-build: |
      mkdir -p "$CRAFT_PART_INSTALL/app" "$CRAFT_PART_INSTALL/bin"

      rsync -a --exclude '.git' --exclude 'venv' ./ "$CRAFT_PART_INSTALL/app/"

      cp -f bin/websocket-wrapper.sh "$CRAFT_PART_INSTALL/bin/"
      chmod +x "$CRAFT_PART_INSTALL/bin/websocket-wrapper.sh"

      python3 -m venv "$CRAFT_PART_INSTALL/venv"
      "$CRAFT_PART_INSTALL/venv/bin/pip" install -U pip setuptools wheel
      "$CRAFT_PART_INSTALL/venv/bin/pip" install -r "$CRAFT_PART_INSTALL/app/requirements.snap.txt"

    webui-assets:
      plugin: dump
      source: package-assets
      organize:
        "*": package-assets/

apps:
  websocket-api:
    command: bin/websocket-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
